### ISSUE TITLE
Add tests that would have caught the bug in version 2.3.2

### ISSUE THREAD

**Issue by forevermatt** [silinternational/simplesamlphp-module-silauth#31]
Delaying the database connection setup resulted in it not being available when we were looking for whether to show a captcha for the current request (due to IP address rate limiting). However, all of our existing tests passed despite that bug. Having that kind of a hole in our automated tests is enough that I'd consider it a bug in itself.

Add some kind of test (ideally actually opening a headless browser of some sort) that would have caught this bug.

**Comment by briskt** [comment]
@forevermatt do you still believe this is worthwhile?

**Comment by forevermatt** [comment]
> @forevermatt do you still believe this is worthwhile?

No, thanks for checking.
