### ISSUE TITLE
Correct typo in eduPersonTargetedId field name... and anything depending on it?

### ISSUE THREAD

**Issue by forevermatt** [silinternational/simplesamlphp-module-silauth#52]
The attributes returned by any IdP using this SilAuth repo currently contain an `eduPersonTargetId` (incorrect) field, rather than an `eduPersonTargetedId` (correct) field:
https://github.com/silinternational/simplesamlphp-module-silauth/blob/8e8eb79b543a5689145f232247e3efb426c997ca/src/saml/User.php#L21

There are a handful of other places where we have also made this mistake:
https://github.com/search?q=org%3Asilinternational+eduPersonTargetID&type=Code

As a first step in resolving this, we'll probably need to make sure no SP's are depending on this mistyped version of that field name.

**Comment by devon-sil** [comment]
Adding to our backlog.

**Comment by forevermatt** [comment]
If I remember correctly, there is also an authproc that we are/should-be using to generate the real eduPersonTargetedId attribute... though that's just going from memory, so it might not be correct. I believe there are places where we are doing this correctly now, so searching our metadata might provide a correct example now. Just for what that's worth.

**Comment by briskt** [comment]
Moved to [ssp-base repo](https://github.com/silinternational/ssp-base/issues/204)
